/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asistensi;
import javax.swing.JOptionPane;
/**
 *
 * @author Windows 10
 */
public class DEVANY_TUGAS2 extends javax.swing.JFrame {

    /**
     * Creates new form GUIaproksimasi
     */
    public DEVANY_TUGAS2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        soal = new javax.swing.JComboBox<>();
        tampilansoal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputa = new javax.swing.JTextField();
        inputn = new javax.swing.JTextField();
        inputx = new javax.swing.JTextField();
        inputh = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("MENGHITUNG APROKSIMASI");

        soal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        soal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Soal", "nomor 4", "nomor 5", "nomor 7" }));
        soal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soalActionPerformed(evt);
            }
        });

        tampilansoal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("input a");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("input n");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("input x");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("hasil");

        inputa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        inputa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputaActionPerformed(evt);
            }
        });

        inputn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        inputn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputnActionPerformed(evt);
            }
        });

        inputx.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        inputx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputxActionPerformed(evt);
            }
        });

        inputh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        inputh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputhActionPerformed(evt);
            }
        });

        hitung.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hitung.setText("hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });

        reset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        reset.setText("reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tampilansoal)
                            .addComponent(soal, 0, 234, Short.MAX_VALUE))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(reset)
                        .addGap(45, 45, 45)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hitung)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputa, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(inputn)
                            .addComponent(inputx)
                            .addComponent(inputh))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 129, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(inputn)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(soal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(tampilansoal, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hitung)
                    .addComponent(reset))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        inputa.setText("");
        inputn.setText("");
        inputx.setText("");
        inputh.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void soalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soalActionPerformed
        // TODO add your handling code here:
        switch(soal.getSelectedIndex()){
            case 1:
                inputa.setText("");
                inputn.setText("");
                inputx.setText("");
                inputh.setText("");
                tampilansoal.setText("f(x) = ln(-x)");
                break;
            case 2:
                inputa.setText("");
                inputn.setText("");
                inputx.setText("");
                inputh.setText("");
                tampilansoal.setText("f(x) = x / (1-x)");
                break;
            case 3:
                inputa.setText("");
                inputn.setText("");
                inputx.setText("");
                inputh.setText("");
                tampilansoal.setText("f(x) = xe^2x ");
                break;
                
        }
    }//GEN-LAST:event_soalActionPerformed
public static double PerhitunganSoal4(double a, double n, double x) {
        double[] f = new double[10001];
        f[0] = Math.log(-a);
        double Fungsi=0;
        double es = 0.5 * Math.pow(10, 2-n);
        for(int p=1; p<=10000; p++){
            f[p]=f[p-1] + (Math.pow(-1,p+1)*Math.pow(x-a, p))/(p*Math.pow(a,p));
            double ea = ((f[p]-f[p-1])/f[p])*100;
            if(Math.abs(ea)<es){
                Fungsi += f[p];
                System.out.println(p);
                break;
            }
        }
        double Output = Math.floor(Fungsi*10000)/10000;
        return Output;
    }
public static double PerhitunganSoal5(double a, double n, double x) {
        double[] f = new double[10001];
        f[0] = a/(1-a);
        double Fungsi=0;
        double es = 0.5 * Math.pow(10, 2-n);
        for(int p=1; p<=10000; p++){
            f[p]=f[p-1]+deret(x, a, p);
            double ea = ((f[p]-f[p-1])/f[p])*100;
            if(Math.abs(ea)<es){
                Fungsi += f[p];
                System.out.println(p);
                break;
            }
            }
        double Output = Math.floor(Fungsi*10000)/10000;
        return Output;
}

public static double PerhitunganSoal7(double a, double n, double x) {
        double[] f = new double[10001];
        f[0] = a*Math.exp(2*a);
        double es = 0.5 * Math.pow(10, 2-n);
        double Fungsi=0;
        double k;
        double l = 1;
        for(int p=1; p<=10000; p++){
            k = Math.pow(2,p);
            f[p] = f[p-1] = (k*a*Math.exp(2*x)+l*Math.exp(2*a))*Math.pow(x-a,p)/faktorial(p);
            l = 2*l+k;
            double ea = ((f[p]-f[p-1])/f[p])*100;
            if(Math.abs(ea)<es){
                Fungsi += f[p];
            }
        }
        double Output = Math.floor(Fungsi*10000)/10000;
        return Output;
}


    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        double a = Double.parseDouble(inputa.getText());
        double n = Double.parseDouble(inputn.getText());
        double x = Double.parseDouble(inputx.getText());
        switch(soal.getSelectedIndex()){
            case 1:
                if(a<0 && x<0){
                    inputh.setText(String.valueOf(PerhitunganSoal4(a,n,x)));
                }else{
                    JOptionPane.showMessageDialog(null, "Input yang dimasukkan salah\n"+"Nilai a dan x harus kurang dari 0");
                }
                break;
            case 2:
                if(a!=1 && (x>-2 && x<2)){
                    inputh.setText(String.valueOf(PerhitunganSoal5(a,n,x)));
                }else{
                    JOptionPane.showMessageDialog(null, "Input yang dimasukkan salah\n"+"Nilai x harus lebih dari -2 dan kurang dari 2");
                }
                break;
            case 3:
                inputh.setText(String.valueOf(PerhitunganSoal7(a,n,x)));
                break;
            default:
                JOptionPane.showMessageDialog(null, "Masukkan Soal");
    }//GEN-LAST:event_hitungActionPerformed
    }
    private void inputaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputaActionPerformed

    private void inputnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputnActionPerformed

    private void inputxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputxActionPerformed

    private void inputhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputhActionPerformed
public static double faktorial(int angka){
    if(angka==1 || angka==0){
        return 1;
    }else{
        return angka*faktorial(angka-1);
    }
}
public static double deret(double x, double a, int suku) {
        double hasil = 1;
        for(int p=1; p<=suku; p++){
            hasil *=(x-a)/(1-a); 
        }
        return hasil;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DEVANY_TUGAS2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DEVANY_TUGAS2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DEVANY_TUGAS2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DEVANY_TUGAS2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DEVANY_TUGAS2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hitung;
    private javax.swing.JTextField inputa;
    private javax.swing.JTextField inputh;
    private javax.swing.JTextField inputn;
    private javax.swing.JTextField inputx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton reset;
    private javax.swing.JComboBox<String> soal;
    private javax.swing.JTextField tampilansoal;
    // End of variables declaration//GEN-END:variables
}
